highlight current page
osscameroon/miniyotas pull request #25
Opened 2022-04-29 18:59 UTC by Mankavelda

2022-05-06 09:10 UTC, elhmn commented
Nice work again, I left a [comment](https://github.com/osscameroon/camerapps.com/pull/44#issuecomment-1119384729) on the other PR. I think once you fixed it on the other PR you could try to apply the same patch to this one 👌

2022-05-12 05:58 UTC, elhmn requested changes

2022-05-12 05:58 UTC, elhmn commented on src/views/partials/pagination.hbs
> +                {{#if (portContains @root.fullUrl "3000") }}
This won't work in production, as the fullUrl  will be something different and probably won't use a port

2022-05-12 06:17 UTC, elhmn requested changes
I tested the implementation and it does not seem to work, if we change the port. Could you test locally and let me know ?

2022-05-13 06:38 UTC, Mankavelda commented on src/helpers/handlebars.ts
> +  return (!(a));
Thanks @elhmn. i will make the changes right away!!!

2024-08-22 12:35 UTC, closed without merging